config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/admins', as: 'rails_admin'
  devise_for :users,
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', sign_up: 'registration'},
             controllers: {
                 registrations: 'users/registrations'
             }
  devise_for :admins, path_names: {sign_in: 'login'}, controllers: {sessions: 'admins/sessions'}

  devise_for :managers, path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret'},
             controllers: {sessions: 'managers/sessions'}


  resource :users, only: [] do
    resources :bills, params: :type, shallow: true do
      resources :transactions, only: %i[show,create]
    end
    get '/:id', to: 'users/main#dashboard', as: 'profile'
  end

  resource :managers, only: [] do
    resources :manager_notifications, :bill_requests, except: %i[create update]
    resource :bills, params: :type
    resources :transactins, only: :show
    get '/:id', to: 'managers/main#dashboard', as: 'profile'
  end

  root to: 'pages#index'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :timeoutable, :lockable, :confirmable

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  validates :email, :full_name, :birthday, :gender, :phone, presence: true
  validates :email, uniqueness: true
  validates :encrypted_password, length: {minimum: 6}, presence: true
  validates :phone, length: {minimum: 9, maximum: 11}
  validates :encrypted_password, confirmation: true, on: %i[create update]
  validates :gender, inclusion: {in: %w(male female)}
  has_many :bills, dependent: :destroy
  validates_associated :bills

  def execute_command(command)
    command.execute
  end


end

app/controllers/users/main_controller.rb
class Users::MainController < ApplicationController

  def dashboard
    @user = User.friendly.find(params[:id])
  end


end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: :create
  before_action :configure_user_update_params, only: :update
  after_action :set_default_bill, only: :create
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  def set_default_bill
    bill_builder = BillService::BillBuilder.new
    resource.bill.create(bill_builder.bill_type = 'deposit')
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name birthday gender phone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_user_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name birthday gender phone])
  end

  # # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/main_helper.rb
module Users::MainHelper
end

app/views/users/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" id="error_explanation " role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="text-center`">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
      %>
    </h3>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_links.html.erb
<div class="link-list">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br/>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_user_registration_path %><br/>
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
      <br/>
    <% end %>
  <% end %>
</div>