config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/admins', as: 'rails_admin'
  devise_for :users,
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', sign_up: 'registration'},
             controllers: {
                 registrations: 'users/registrations'
             }
  devise_for :admins, path_names: {sign_in: 'login'}, controllers: {sessions: 'admins/sessions'}

  devise_for :managers, path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret'},
             controllers: {sessions: 'managers/sessions'}


  resource :users, only: [] do
    resources :bills, params: :type, shallow: true do
      resources :transactions, only: %i[show,create]
    end
    get '/:id', to: 'users/main#dashboard', as: 'profile'
  end

  resource :managers, only: [] do
    resources :manager_notifications, :bill_requests, except: %i[create update]
    resource :bills, params: :type
    resources :transactins, only: :show
    get '/:id', to: 'managers/main#dashboard', as: 'profile'
  end

  root to: 'pages#index'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable, :timeoutable,
         :trackable, :authentication_keys => [:login]
  validates :login, presence: true, uniqueness: true

  def email_required?
    false
  end


  def will_save_change_to_email?
    false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  validates :bill_type, :amount, presence: true
  validates :bill_type, inclusion: {in: %w[credit deposit]}
  validates :amount, numericality: true
  has_many :make_transactions, class_name: 'Transaction', foreign_key: 'sender_id', dependent: :destroy
  has_many :get_transactions, class_name: 'Transaction', foreign_key: 'recipient_id', dependent: :destroy
  has_many :manager_notifications
  has_one :bill_request, dependent: :destroy
  validates_associated :make_transactions, :get_transactions, :bill_request
  attr_accessor :name
end

app/models/bill_request.rb
class BillRequest < ApplicationRecord
  validates :message, :bill, :manager, presence: true
  belongs_to :bill
  belongs_to :manager
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :short_code, presence: true, uniqueness: true
  has_many :cities, dependent: :destroy
  validates_associated :cities
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :timeoutable, :trackable, :authentication_keys => [:login]
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  validates :login, :email, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates :encrypted_password, length: {minimum: 6}
  has_many :bill_requests, dependent: :delete_all
  has_many :manager_notifications
  validates :encrypted_password, confirmation: true, on: :update
  validates_associated :bill_requests, :manager_notifications
end

app/models/manager_notification.rb
class ManagerNotification < ApplicationRecord
  validates :message, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sender, class_name: 'Bill', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'Bill', foreign_key: 'recipient_id'
  validates :sender, :recipient, presence: true
  validates :amount, presence: true, numericality: true
  validates_associated :recipient, :sender
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :timeoutable, :lockable, :confirmable

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  validates :email, :full_name, :birthday, :gender, :phone, presence: true
  validates :email, uniqueness: true
  validates :encrypted_password, length: {minimum: 6}, presence: true
  validates :phone, length: {minimum: 9, maximum: 11}
  validates :encrypted_password, confirmation: true, on: %i[create update]
  validates :gender, inclusion: {in: %w(male female)}
  has_many :bills, dependent: :destroy
  validates_associated :bills

  def execute_command(command)
    command.execute
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_account
  helper_method :authenticate_account

  def current_account
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    elsif session[:manager_id]
      @current_user_user ||= User.find(session[:manager_id])
    else
      @current_user = nil
    end
  end

  def authenticate_account
    unless current_user
      flash[:alert] = 'You need to sign in or sign up'
      redirect_to root_path
    end
  end


end

app/controllers/bill_requests_controller.rb
class BillsRequestController < ApplicationController

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create

  end


  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/manager_notifications_controller.rb
class ManagerNotificationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to profile_users_path(current_user)
    elsif manager_signed_in?
      redirect_to profile_managers_path(current_manager)
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {success: 'alert-success',
     error: 'alert-danger',
     alert: 'alert-danger',
     notice: 'alert-info',
    }[name.to_sym] || name
  end


  def user_menu
    {name: 'Bill', sub_menu: [
        {name: 'Credits', path: :users_bills, type: 'deposit'},
        {name: 'Deposits', path: :users_bills, type: 'credits'},
        {name: 'New credit', path: :new_users_bill, type: 'deposit'},
        {name: 'New deposit', path: :new_users_bill, type: 'credits'}]}
  end

end

app/helpers/managers/main_helper.rb
module Managers::MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users/main_helper.rb
module Users::MainHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |name, message| %>
      <div class="alert alert-dismissible fade show <%= bootstrap_class_for(name) %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetBanking</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <nav class="navbar navbar-expand navbar-dark bg-dark ">
    <a href="<%= root_path %>"><%= image_tag('nav.svg', size: '45x45') %></a>
    <% if current_user %>
      <%= render 'users/main/menu' %>
    <% end %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <%= render 'shared/login_panel' %>
    </div>
  </nav>
</header>
<%= render 'layouts/messages' %>
<%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<div class="bg_image">

</div>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" id="error_explanation " role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="text-center`">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
      %>
    </h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>'
    </ul>
  </div>
<% end %>

app/views/shared/_login_panel.html.erb
<ul class="navbar-nav ">
  <% if current_user %>
    <li class="nav-item active">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' %>
    </li>
  <% elsif current_manager %>
    <%= link_to 'Logout', destroy_manager_session_path, method: :delete, class: 'btn btn-outline-primary' %>

  <% else %>
    <li class="nav-item active">
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary' %>
      <%= link_to 'Registration', new_user_registration_path, class: 'btn btn-outline-primary' %>
    </li>
  <% end %>
</ul>